### ISSUE TITLE
How long does it take to run vision_attribution.ipynb?

### ISSUE THREAD

**Issue by mburaksayici** [CAMP-eXplain-AI/InputIBA#21]
Hi everyone,
Ild like to learn how long does it take to have explanations on cpu device. Its been half and hour and I only have plt.show() executed.

**Comment by sandylaker** [comment]
Hi, 
 thanks for your interest in our work. So on a single machine with a Ryzen 9 CPU and RTX3090, it takes appox. 24 seconds to get attribution maps for one 224×224 image, if using the default configs for VGG16 that we provide in the `configs/` folder. 

But we did not check how long it takes to process on CPUs. We suggest you to first run the code on GPU. So that we can know if it is caused by our implementation or by computation resource. 

Best regards.

**Comment by sandylaker** [comment]
Hi, 
 thanks for your interest in our work. So on a single machine with a Ryzen 9 CPU and RTX3090, it takes appox. 24 seconds to get attribution maps for one 224×224 image, if using the default configs that we provide in the `configs/` folder. 

But we did not check how long it takes to process on CPUs. We suggest you to run the code on GPU. So that we can know if it is caused by our implementation or by computation resource.
