### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by OverfitFlow** [CAMP-eXplain-AI/InputIBA#28]
Hi,

This is excellent work, and thank you for sharing the well-designed official codes for a better understanding of the details of your NeurIPS paper.

I would like to understand the details of some equations, and I'd appreciate it if you could explain them to me.
In your paper, you proposed two assumptions for estimating the $I[I, Z]$,
which are $Z_I = \Lambda Z_{G} + (1 - \Lambda) \epsilon$ and $Z_G = \lambda_G Z_{I} + (1 - \lambda_G) \epsilon_{G}$,

1) the term $\epsilon$ is only mentioned again in the $Z^* = \lambda^* R + (1-\lambda^{*}) \epsilon$ for feature IBA,
can I assume they are **not** the same?
2) in order to derive remark 2 (equation 9) in your paper, can I assume the $\epsilon$ for $Z_I$ is actually equal to $\epsilon_G$ , so that I can merge those two epsilon terms together?
3) based on the above, the $\mu_I$ and $\sigma_I$ are actually $\mu_G$ and $\sigma_G$ in remark 2 and equation 9
4) if my understanding above is wrong, could you please let me know how can I get the remark 2, as $\epsilon_G$ is a Gaussian parameterized by learnable parameters $\mu_G$ and $\sigma_G$, but the parameters of $Z_I$'s distribution is related with $\mu_I$ and $\epsilon_I.$

**Comment by YaNgZhAnG-V5** [comment]
Hi,

thanks for your interest for our work. 

About the term $\epsilon$, For $Z_I$ and $Z_G$, they are indeed the same in our implementation. The intuition is because both $Z_I$ and $Z_G$ are related to the input, which is an image in the CV task, and a sentence in the NLP task. The important thing is that, they both related to the actual input, so we can **define** a proper noise based on the actual task. In terms of an image input, the noise is a zero mean Gaussian noise (can be interpreted as black pixels, as we assume black has no information). For NLP this can still be a zero mean Gaussian, since in the embedding space, this corresponds to the "unknown" token.

And about remark 2 and equation 9, yes the two noises are identical in our formular, as you mentioned this can ease the derivation. Also, they are identical because they have the same physical meaning mentioned above respectively. Still, learn a noise $\epsilon_G$ is theoretically feasible, but will be computationally more complex, as the term $Z_I$ will be more complex as you mentioned. Nevertheless, $Z_I$ is still a Gaussian even when $\epsilon_I$ and $\epsilon_G$ are not the same. So we can still calculate the mutual information in this case.

Let me know if you have further questions :)

**Comment by OverfitFlow** [comment]
Hi Yang,

Thanks for your reply.

I am still confused with the term $\epsilon$ you used for learning the input mask $\Lambda$.
As you used the GAN to learn the parameters ($\mu_{G}$ and $\sigma_{G}$) of $\epsilon_{G}$, and based on what you explained to me, the parameters of $\epsilon_G$ should be used for learning the input mask $\Lambda$. Since we ease the derivation based on them.

However, it seems that the $\mu$ and $\sigma$ (line 69-71 input_iba/models/bottlenecks/vision_input_iba.py) you used for constructing the mutual information loss (line 73) are still 0 and 1, not the learned one from GAN.
Could you please explain it to me as well? Thank you in advance for your help.

Or why not just make the $\lambda_{G}$ the only learnable variable instead of $\lambda_{G}$, $\mu_{G}$ and $\sigma_{G}$ ? so that the $\mu$ and \sigma\ for both distribution $p(Z_I)$ and $p(Z_I \mid Z_G)$ in the derivation of KL loss straightforward are identical.

**Comment by YaNgZhAnG-V5** [comment]
Hi Jueqing,

I just check the code, and seems like we are using all $\mu_G$, $\sigma_G$ and $\lambda_G$ as learning parameters in the generator, this is not what we intended, thanks for pointing that out. However, this implementation bug shouldn't affect the performance too much, as both $\mu_G$ and $\sigma_G$ have only 3 learnable parameters (RGB channels), which are significantly less than the learnable parameters in $\lambda_G$.

In theory, GAN can be used to learn $\mu_G$, $\sigma_G$ and $\lambda_G$ simultaneously. In our implementation, what we intended is to learn only the $\lambda_G$, as explained previously. Since the task is very specific, and we know what kind of noise would result to minimal information (in the CV case is the black pixel). If for certain task, it is not very clear which kind of noise can result in minimal information, then it is better to learn the noise together with the input mask. 

Again, thank you for pointing this out.

Yang

**Comment by OverfitFlow** [comment]
Hi Yang,

Thank you for the clarification.
So in summarization, you intended to learn only $\lambda_G$ for constructing $Z_G$, and the $\epsilon_G$ is actually a Gaussian with $\mu$ = 0 and $sigma$ = 1, which is identical to $\epsilon_I$?

**Comment by YaNgZhAnG-V5** [comment]
Hi Jueqing,

Yes, for the tasks shown in the paper, this setting is appropriate enough. If you are exploring other type of tasks, then you need to think about a proper input noise fit for your task. N(0, 1) is not always the right choice :)

**Comment by OverfitFlow** [comment]
thank you for your suggestion and feedback
